[project]
name = "pop_lab"
version = '0.0.1'

dependencies = [
    "pandas",
    "numpy",
    "matplotlib",
    "pytest",
    "pynei"
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
